config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :bookings do
    member do
      patch 'cancel'
    end
  end
  devise_for :users
    get 'profile', to: 'pages#profile', as: "profile"
    root to: "restaurants#index"

  resources :restaurants do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user 
  belongs_to :restaurant
  enum status: [:pending, :confirmed, :canceled]
  # Add any other necessary validations or methods
  validates :booking_date, :booking_time, :party_size, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  # validates :image, presence: true
  # serialize :type, Array
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable

  has_many :bookings
  # validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_one_attached :avatar 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_restaurant, only: %i[ new create]

  def show
    @booking = Booking.all
  end

  def new
    @booking = Booking.new
  end

def create
  @booking = Booking.new(booking_params)
  @booking.user = current_user
  @booking.restaurant = @restaurant
    if @booking.save
    redirect_to profile_path, notice: "Booking created"
    # needs to go confiramtion page
  else
    render "bookings/new", status: :unprocessable_entity
  end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
  @booking = Booking.find(params[:id])
  if @booking.update(booking_params)
    # Handle successful update
    redirect_to profile_path, notice: 'Booking was successfully updated.'
  else
    # Handle validation errors or other errors
    render :edit
  end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, status: :see_other
  end


private

def booking_params
  params.require(:booking).permit(:party_size, :booking_date, :booking_time)
end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/concerns/bookings_controller.rb
# app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user! # Assuming Devise for authentication

  def cancel
    @booking = current_user.bookings.find(params[:id])

    if @booking.update(status: :canceled)
      redirect_to user_bookings_path, notice: 'Booking canceled successfully.'
    else
      redirect_to user_bookings_path, alert: 'Failed to cancel booking.'
    end
  end

  # Add other actions (index, show, create, etc.) as needed
end

app/controllers/concerns/restaurants_controller.rb
# app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @bookings = @restaurant.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def profile
      @user = current_user
      @bookings = @user.bookings
    end
  end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @booking = Booking.new
  end

  def vegetarian!
    @vegetarian = Restaurant.vegetarian


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :booking_date, as: :string, input_html: { class: 'datepicker' } %>
    <%= f.input :booking_time %> <!-- Assuming you have a time picker -->
    <%= f.input :party_size %>
    <!-- You may include other attributes as per your requirement -->
  </div>

  <div class="form-actions">
    <%= f.button  :submit %>
  </div>
<% end %>

<script>
  $(function() {
    $('.datepicker').datepicker({ dateFormat: 'yy-mm-dd' });
  });
</script>

app/views/bookings/form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :party_size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    


    </div>
<% end %>

app/views/bookings/index.html.erb
# app/views/bookings/index.html.erb
<h1>Your Bookings</h1>

<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= "#{booking.booking_date} at #{booking.booking_time}" %> - <%= booking.status %>
      <%= link_to 'Cancel', cancel_booking_path(booking), method: :patch, data: { confirm: 'Are you sure you want to cancel this booking?' } %>
    </li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="imageHeader">
  <%= image_tag @restaurant.image, class: "card-img-top" %>
</div>

<div class=" flex-wrap">
<div class="rightCol">





<%# restaurant info %>

<div id="listOfRestautants">

      <!-- START of Go back Button -->
      <!-- END of Go back Button -->
      <!-- START Image Slider -->
      <!-- END Image Slider -->

      <!-- start Restaurant Title -->
      <div class="restaurantTitle">
          <h2><%= @restaurant.name %></h2>
      </div>
      <!-- END Restaurant Title -->

      <!-- start Restaurant Rating - Price - OpenNow-->
      <div class="restaurant-Rate-Price-OpenNow">

          <div class=" restaurant-rating-scoreVar ">


              <div class="restaurant-rating-scoreVar restaurant-rating" style="background-image: url(<%= asset_path('ratingbackground.svg') %>) ">
                 <img class="Popular-rating-score rating-score" src="<%= asset_path('ratingscore.svg') %>" width="<%= (@restaurant.ratings * 100) / 5 %>%"   alt=" ">
              </div>


              <div class=" rateScorVar "><%= @restaurant.ratings %></div>
          </div>


          <div class="divider"></div>
          <div class="restaurant-Price">€€€</div>
          <div class="divider"></div>
          <div class=" restaurant-OpenNow ">
              <p>Open now</p>
              <img src="<%= asset_path('Open-now-Icon.svg') %>" alt=" ">
          </div>
      </div>
      <!-- END Restaurant Rating - Price - OpenNow-->


      <!-- start Restaurant Cuisine / DietaryRestriction / Delivery -->
      <div class="restaurant-Cuisine-DietaryRestriction-Delivery">
          <div class="restaurant-Cuisine CuisineContainer">
              <div class="CuisineImg">
                <img src="<%= asset_path("#{@restaurant.category}.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p><%= @restaurant.category %></p>

              </div>
          </div>
          <div class="categoryDivider"></div>
          <div class="restaurant-DietaryRestriction CuisineContainer">
              <div class="CuisineImg">
                  <img src="<%= asset_path("Kosher.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p><%= @restaurant.dietaryRestrictions %></p>
              </div>
          </div>
          <div class="categoryDivider"></div>
          <div class="restaurant-Delivery CuisineContainer">
              <div class="CuisineImg">
                  <img src="<%= asset_path("pickup.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p>pickup</p>
              </div>
          </div>

      </div>
      <!-- END Restaurant Cuisine / DietaryRestriction / Delivery -->


      <!-- start Restaurant Description -->
      <div class="restaurantDescription">
          <p><%= @restaurant.description %></p>
      </div>
      <!-- End Restaurant Description -->

      <!-- start Restaurant Address -->
      <div class="restaurant-Address">
          <img class="Img-Icon" src="<%= asset_path("adressIcon.svg") %>" alt=" ">
          <div class="textInfo"><%= @restaurant.address %></div>
      </div>
      <!-- END Restaurant Address -->

      <!-- start Restaurant Phone Number -->
      <div class=" restaurant-tel ">
          <img class="Img-Icon" src="<%= asset_path("phoneIcon.svg") %>"alt=" ">

          <div class="textInfo"><%= @restaurant.phone_number %></div>
      </div>
      <!-- END Restaurant Phone Number -->

      <!-- start Restaurant OpningTime -->
      <div class="restaurant-OpningTime">
          <img class="Img-Icon" src="<%= asset_path("Open-now-Icon.svg") %>"alt=" ">
          <div class="textInfo">
              From 9:00 to 23:00
              <%= @restaurant.opening_hours %>
          </div>

      </div>
      <!-- END Restaurant OpningTime -->

  </div>







</div>
<div class="booking">

<%= simple_form_for [@restaurant , @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :booking_date %>
    <%= f.input :booking_time %>
    <%= f.input :party_size %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add booking", class: 'btn btn-primary'  %>
        </div>
<% end %>

<form action=""></form>

</div>

</div>

<div class="" style="width: 18rem;">


</div>

<%= link_to "booking", new_restaurant_booking_path(@restaurant), class: "btn btn-primary" %>

app/views/bookings/update.html.erb
<h1>my booking</h1>
<li>
  <ul><%= @user.booking.each do |bookings| %> </ul>
</li>




<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">cancel booking</a>
    <a class="dropdown-item" href="#">update booking</a>
      </div>
</div>

app/views/bookings/view.html.erb
git<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :party_size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirResturant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js' %>
  <%= stylesheet_link_tag 'https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css' %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <!-- Login Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="loginModalLabel">Login</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <!-- Add your login form here -->
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
    <%= yield %>
    </div>


    <!-- Bootstrap JS (optional, if you need dropdowns, modals, etc.) -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>

<%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/restaurants/index.html.erb
# app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

app/views/layouts/restaurants/show.html.erb
# app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><strong>Address:</strong> <%= @restaurant.address %></p>
<p><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>
<p><strong>Description:</strong> <%= @restaurant.description %></p>
<p><strong>Vegetarian:</strong> <%= @restaurant.vegetarian ? 'Yes' : 'No' %></p>

<h2>Bookings</h2>
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= "#{booking.booking_date} at #{booking.booking_time}" %> - <%= booking.status %>
    </li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<!-- - create custom routes for profile
- create profile method in pages controller
- create view for profile.html.erb inside pages views folder
- current_user.bookings -->

<%# booking Card %>

<div class="">



    <% @user.bookings.each do |booking| %>


 <div class="bookingdiv">

<div class="Popular-restaurant-info">
  <div class="Popular-restaurant-img">
        <a href="#"><img class=" Popular-restaurant-img-link " src="<%= booking.restaurant.image %>" alt=" "></a>
    </div>
    <div class=" Popular-restaurant-text-info ">
        <div class="Popular-restaurant-text-Title-favoriteIcon ">

            <h3 class=" Popular-restaurant-title "><a href="#"><%= booking.restaurant.name %></a>
            </h3>

        </div>

        <div class=" Popular-restaurant-description ">
            <p><%= booking.restaurant.description %>
            </p>
        </div>

        <div class=" Popular-restaurant-rating-scoreVar ">
            <div class="Popular-restaurant-rating-wrapper">
            <div class="Popular-restaurant-rating" style="background-image: url(<%= asset_path('ratingbackground.svg') %>) ">
               <img class="Popular-rating-score" src="<%= asset_path('ratingscore.svg') %>" width="<%= (booking.restaurant.ratings * 100) / 5 %>%"    alt=" ">
            </div>



                <div class=" Popular-rateScorVar "><%= booking.restaurant.ratings %></div>




            </div>
            <div class=" Popular-restaurant-OpenNow ">
                <p>Open now</p>
                <img src="<%= asset_path('Open-now-Icon.svg') %>" alt=" ">
            </div>
        </div>



        <div class=" Popular-restaurant-tel-cuisine-openNow ">




        </div>
    </div>

</div>


      <div class="">

      <div class="bookinginfo">
      <div id="bookingwild">
        <h5>Your booking information</h5>
        <h4><%= booking.restaurant.name %></h4>
         <div class="inforestaurantbooking">

        <div class="restaurant-Address">
            <img class="Img-Icon" src="/assets/adressIcon-9b5480c829a84d0145f4b452f421c50c081a6941bf1428316a887a06ceb36c21.svg" alt=" ">
            <div class="textInfo"><%= booking.restaurant.address %></div>
        </div>

        <div class=" restaurant-tel ">
            <img class="Img-Icon" src="/assets/phoneIcon-603110e6c78f6977d858d4486cb2f988b91f88ecb7cf190127f1729b472edfb2.svg" alt=" ">

            <div class="textInfo"><%= booking.restaurant.phone_number %></div>
        </div>

        <div class="restaurant-OpningTime">
            <img class="Img-Icon" src="/assets/Open-now-Icon-11edcfd53de93dd8ff2587dc749fd7f59a90b43246d09e25017951d4fcdd3b74.svg" alt=" ">
            <div class="textInfo"><%= booking.booking_date %></div>
            <div class="textInfo"><%= booking.booking_time %></div>

        </div>
      </div>

      <div class="bookingeditBtn">
            <%= button_to "Delete", booking_path(booking), method: :delete, class: 'button-delete' %>
            <%= button_to "Update", edit_booking_path(booking), method: :get, class: 'button-edit' %>
      </div>


  </div>
  </div>
   <% end %>
  </div>


      </div>

app/views/restaurants/index.html.erb
<div class="flex-wrap">

<%# restaurant card %>

  <% @restaurants.each do |restaurant| %>
    <div class="mx-2 mb-4 zoom-effect">



<div class="Popular-restaurant-info">
  <div class="Popular-restaurant-img">
        <a href="<%= restaurant_path(restaurant) %>"><img class=" Popular-restaurant-img-link " src="<%= restaurant.image %>" alt=" "></a>
    </div>
    <div class=" Popular-restaurant-text-info ">
        <div class="Popular-restaurant-text-Title-favoriteIcon ">

            <h3 class=" Popular-restaurant-title "><a href="<%= restaurant_path(restaurant) %>"><%= restaurant.name %></a>
            </h3>

        </div>

        <div class=" Popular-restaurant-description ">
            <p><%= restaurant.description %>
            </p>
        </div>

          <div class=" restaurant-category-tag ">
         <%= restaurant.category %>
        </div>

        <div class=" Popular-restaurant-rating-scoreVar ">
            <div class="Popular-restaurant-rating-wrapper">
            <div class="Popular-restaurant-rating" style="background-image: url(<%= asset_path('ratingbackground.svg') %>) ">
               <img class="Popular-rating-score" src="<%= asset_path('ratingscore.svg') %>" width="<%= (restaurant.ratings * 100) / 5 %>%"   alt=" ">
            </div>



                <div class=" Popular-rateScorVar "><%= restaurant.ratings %></div>




            </div>
            <div class=" Popular-restaurant-OpenNow ">
                <p>Open now</p>
                <img src="<%= asset_path('Open-now-Icon.svg') %>" alt=" ">
            </div>
        </div>



        <div class=" Popular-restaurant-tel-cuisine-openNow ">




        </div>
    </div>

</div>























    <%= link_to restaurant_path(restaurant), class: "" do %>





      <% end %>

    </div>




  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="imageHeader">
  <%= image_tag @restaurant.image, class: "card-img-top" %>
</div>

<div class=" flex-wrap">
<div class="rightCol">





<%# restaurant info %>

<div id="listOfRestautants">

      <!-- START of Go back Button -->

      <!-- END of Go back Button -->

      <!-- START Image Slider -->

      <!-- END Image Slider -->


      <!-- start Restaurant Title -->
      <div class="restaurantTitle">
          <h2><%= @restaurant.name %></h2>
      </div>
      <!-- END Restaurant Title -->

      <!-- start Restaurant Rating - Price - OpenNow-->
      <div class="restaurant-Rate-Price-OpenNow">

          <div class=" restaurant-rating-scoreVar ">


              <div class="restaurant-rating-scoreVar restaurant-rating" style="background-image: url(<%= asset_path('ratingbackground.svg') %>) ">
                 <img class="Popular-rating-score rating-score" src="<%= asset_path('ratingscore.svg') %>" width="<%= (@restaurant.ratings * 100) / 5 %>%"   alt=" ">
              </div>


              <div class=" rateScorVar "><%= @restaurant.ratings %></div>
          </div>


          <div class="divider"></div>
          <div class="restaurant-Price">€€€</div>
          <div class="divider"></div>
          <div class=" restaurant-OpenNow ">
              <p>Open now</p>
              <img src="<%= asset_path('Open-now-Icon.svg') %>" alt=" ">
          </div>
      </div>
      <!-- END Restaurant Rating - Price - OpenNow-->


      <!-- start Restaurant Cuisine / DietaryRestriction / Delivery -->
      <div class="restaurant-Cuisine-DietaryRestriction-Delivery">
          <div class="restaurant-Cuisine CuisineContainer">
              <div class="CuisineImg">


                <img src="<%= asset_path("#{@restaurant.category}.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p><%= @restaurant.category %></p>
              </div>
          </div>
          <div class="categoryDivider"></div>
          <div class="restaurant-DietaryRestriction CuisineContainer">
              <div class="CuisineImg">
                  <img src="<%= asset_path("Kosher.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p><%= @restaurant.dietaryRestrictions %></p>
              </div>
          </div>
          <div class="categoryDivider"></div>
          <div class="restaurant-Delivery CuisineContainer">
              <div class="CuisineImg">
                  <img src="<%= asset_path("pickup.svg") %>" alt="">
              </div>
              <div class="CuisineTitle">
                  <p>pickup</p>
              </div>
          </div>

      </div>
      <!-- END Restaurant Cuisine / DietaryRestriction / Delivery -->


      <!-- start Restaurant Description -->
      <div class="restaurantDescription">
          <p><%= @restaurant.description %></p>
      </div>
      <!-- End Restaurant Description -->

      <!-- start Restaurant Address -->
      <div class="restaurant-Address">
          <img class="Img-Icon" src="<%= asset_path("adressIcon.svg") %>" alt=" ">
          <div class="textInfo"><%= @restaurant.address %></div>
      </div>
      <!-- END Restaurant Address -->

      <!-- start Restaurant Phone Number -->
      <div class=" restaurant-tel ">
          <img class="Img-Icon" src="<%= asset_path("phoneIcon.svg") %>"alt=" ">

          <div class="textInfo"><%= @restaurant.phone_number %></div>
      </div>
      <!-- END Restaurant Phone Number -->

      <!-- start Restaurant OpningTime -->
      <div class="restaurant-OpningTime">
          <img class="Img-Icon" src="<%= asset_path("Open-now-Icon.svg") %>"alt=" ">
          <div class="textInfo">
              From 9:00 to 23:00
              <%= @restaurant.opening_hours %>
          </div>

      </div>
      <!-- END Restaurant OpningTime -->

  </div>







</div>

<div class="booking">

<%= simple_form_for [@restaurant , @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :booking_date, input_html: { class: 'inputstyle' }%>
    <%= f.input :booking_time, input_html: { class: 'inputstyle' }%>
    <%= f.input :party_size, input_html: { class: 'inputstyle' }%>
  </div>

  <div class="form-actions">
    <%= f.submit "Add booking", class: 'button-5'  %>
        </div>
<% end %>

</div>

</div>

<div class="" style="width: 18rem;">


</div>

app/views/shared/_footer.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to "/restaurants", class: "navbar-brand" do %>
      <%= image_tag "logo.svg", style: "width: 350px;     opacity: 5%;", alt: "Logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to "/restaurants", class: "navbar-brand" do %>
      <%= image_tag "logo.svg", style: "width: 250px;", alt: "Logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%# <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user %>
          <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, class: "avatar", alt: "dropdown menu",crop: :fit%>
          <% else %>
    <%= image_tag "https://aui.atlassian.com/aui/8.6/docs/images/avatar-person.svg", class: "avatar", alt: "dropdown menu" %>
  <% end %>
<% end %>

          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>